name = "anubis-db"
main = "src/worker.ts"
compatibility_date = "2026-05-17"
routes = [
  { pattern = "anubisdb.com/*", zone_name = "anubisdb.com" },
  { pattern = "www.anubisdb.com/*", zone_name = "anubisdb.com" },
]

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "anubis-db"
database_id = "450aad16-6f6d-4743-bd4b-2fe0b03b8eba"
